# Generated by Django 2.1.5 on 2019-08-21 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 12, 40, 15, 905089)),
        ),
    ]
